version: '3.5'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: todo_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "400:80"
      - "401:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #Postgress Service
  db:
    image: postgres
    container_name: todo_db
    restart: unless-stopped
    ports:
      - "407:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    name: todo
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
